### ISSUE TITLE
 `method_missing': undefined method `this'

### ISSUE THREAD

**Issue by bolom** [packsaddle/ruby-github_status_notifier#15]
when i have run the command

> github-status-notifier notify --state pending

I have got this error

```
bolo:guava.backend Michelin$ github-status-notifier notify --state pending
/Users/Michelin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fd4420ecdf0 github_status_notifier-0.1.2> (NoMethodError)
    from /Users/Michelin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
    from /Users/Michelin/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
    from /Users/Michelin/.rvm/gems/ruby-2.3.1/gems/github_status_notifier-0.1.2/exe/github-status-notifier:3:in `<top (required)>'
    from /Users/Michelin/.rvm/gems/ruby-2.3.1/bin/github-status-notifier:23:in `load'
    from /Users/Michelin/.rvm/gems/ruby-2.3.1/bin/github-status-notifier:23:in `<main>'
    from /Users/Michelin/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/Michelin/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

```

ruby version 2.3.0

**Comment by sanemat** [comment]
Thank you for your reporting, I'll investigate this.
